/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as contractsNew from "./contracts-new";
export * as contractsUpgradeableNew from "./contracts-upgradeable-new";
