version: "3.2"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  keeper:
    image: zerodao/keeper
    build:
      context: ./
      dockerfile:
        packages/watcher/Dockerfile
    restart: unless-stopped
