[profile.default]
src = 'contracts'
out = 'out'
libs = ["lib"]

allow_paths = [
  "../../"
]
via_ir = true
optimizer = true
optimizer_runs = 2000

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/816df2901a454b18b7df259e61f92cd2"
optimism = "https://mainnet.optimism.io"
arbitrum = "https://arb1.arbitrum.io/rpc"
avalanche = "https://api.avax.network/ext/bc/C/rpc"
polygon = "https://polygon-mainnet.infura.io/v3/816df2901a454b18b7df259e61f92cd2"

[etherscan]
mainnet = { key = "34W9GX5VZDJKJKVV6YEAMQ3TDP7R8SR633" }
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
