/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contractsNew from "./contracts-new";
export type { contractsNew };
import type * as contractsUpgradeableNew from "./contracts-upgradeable-new";
export type { contractsUpgradeableNew };
