/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  Bip340Verifier,
  Bip340VerifierInterface,
} from "../../../../bip340-solidity/contracts/Bip340.sol/Bip340Verifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "px",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "rx",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "s",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "m",
        type: "bytes32",
      },
    ],
    name: "verify",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Bip340Verifier__factory {
  static readonly abi = _abi;
  static createInterface(): Bip340VerifierInterface {
    return new utils.Interface(_abi) as Bip340VerifierInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Bip340Verifier {
    return new Contract(address, _abi, signerOrProvider) as Bip340Verifier;
  }
}
