export type Config = {
  RPC: any;
  P2P: any;
  Mempool: any;
  StateSync: any;
  BlockSync: any;
  Consensus: any;
  Storage: any;
  TxIndex: any;
  Instrumentation?: any;
}; /*{
  RPC: RPCConfig;
  P2P: P2PConfig;
  Mempool: MempoolConfig;
  StateSync: StateSyncConfig;
  BlockSync: BlockSyncConfig;
  Consensus: ConsensusConfig;
  Storage: StorageConfig;
  TxIndex: TxIndexConfig;
  Intrumentation?: InstrumentationConfig;
}; */
